kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings: []
    relabelings: []

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
    scrapeTimeout: 10s
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
        cpu: 400m
